### ISSUE TITLE
Process for getting SSL/TLS certs

### ISSUE THREAD

**Issue by rm-rf-etc** [hobby-kube/provisioning#30] opened 2018-08-06 03:36 UTC
Question for you, @pstadler:

The [kube-lego project is "in maintenance mode only", and "The latest Kubernetes release that kube-lego officially supports is 1.8"](https://github.com/jetstack/kube-lego), which appears to be 3 minor versions behind right now. While kube-lego directs people to use [cert-manager](https://github.com/jetstack/cert-manager/), the cert-manager readme states, "This project is not yet ready to be a component in a critical production stack". I want to know if you'd be open to a PR for switching hobby-kube to the [Docker Certbot image](https://hub.docker.com/r/certbot/certbot/), like [described in this guide](https://www.humankode.com/ssl/how-to-set-up-free-ssl-certificates-from-lets-encrypt-using-docker-and-nginx).

For me it seems the certs portion of this project didn't work, but I have to investigate to figure out what happened.

I am just wanting to make contributions where I can. I'm learning as I go, and learning from working with this project.

**Comment by rm-rf-etc** [comment] 2018-08-06 11:10
This is probably more appropriate: https://github.com/kelseyhightower/kube-cert-manager

**Comment by pstadler** [comment] 2018-08-07 07:06
Duplicate of https://github.com/hobby-kube/guide/issues/47

**Closed by pstadler** 2018-08-07 07:06 UTC

**Comment by rm-rf-etc** [comment] 2018-08-09 21:55
This doesn't answer my question. I want to know if there's an alternative you'd endorse so I could submit a PR for something that's wanted.

I suggested Certbot since it's the official Let's Encrypt system, but it seems that this isn't in favor with k8s users.
